import { BarChart3, ClipboardList, Database, FlaskConical, Package } from 'lucide-react'
import { timeAgo } from '../utils/formatters'

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', path: '/dashboard', icon: BarChart3, roles: ['admin', 'operario'] },
  { id: 'controles', label: 'Controls', path: '/controles', icon: ClipboardList, roles: ['admin', 'operario'] },
  { id: 'productos', label: 'Products', path: '/productos', icon: Package, roles: ['admin'] },
  { id: 'tipos', label: 'Types', path: '/tipos', icon: FlaskConical, roles: ['admin'] },
  { id: 'tanques', label: 'Tanks', path: '/tanques', icon: Database, roles: ['admin'] },
]

export const CRUD_RESOURCES = {
  controles: {
    id: 'controles',
    title: 'Daily Control',
    eyebrow: 'Management',
    endpoint: '/controles',
    listEndpoint: '/controles/balance',
    idLabel: 'idControl',
    getId: (item) => item.idControl,
    getTitle: (item) => `Control #${item.idControl}`,
    getSubtitle: (item) => item.producto?.nombre || item.operario,
  stickyFilterColumns: 2,
  listColumnFilters: [
      {
        label: 'GENERAL',
        columns: [
          { label: '#', getValue: (item, index) => index + 1 },
          { label: 'Update', getValue: (item) => timeAgo(item.fecha) },
          { label: 'Chocolate', getValue: (item) => item.tipoChocolate?.categoria },
          { label: 'Product', getValue: (item) => item.producto?.nombre },
        ],
      },
      {
        label: 'PRODUCTION',
        columns: [
          { label: 'Total Physical (lb)', getValue: (item) => item.totalesSistema?.totalChocolateFisico?.toFixed(2) },
          { label: 'Total System (lb)', getValue: (item) => item.totalesSistema?.totalChocolateTeoricoSistema?.toFixed(2) },
          { label: 'To Add', getValue: (item) => item.totalesSistema?.ajusteAdicionRetiro?.toFixed(2) },
          { label: 'To Remove', getValue: (item) => item.totalesSistema?.ajusteRetiro ? `-${item.totalesSistema.ajusteRetiro.toFixed(2)}` : '0.00' },
        ],
      },
      {
        label: 'LOCATIONS',
        columns: [
          { label: 'Molds', getValue: (item) => item.calculosLibras?.enMoldes?.toFixed(2) },
          { label: 'Belt', getValue: (item) => item.calculosLibras?.enBanda?.toFixed(2) },
          { label: 'Morcos', getValue: (item) => item.calculosLibras?.enTanqueMorcos?.toFixed(2) },
          { label: 'Temper', getValue: (item) => item.calculosLibras?.enTemperUnit?.toFixed(2) },
          { label: 'PTI', getValue: (item) => item.calculosLibras?.enTanquePti?.toFixed(2) },
          { label: 'Hopper', getValue: (item) => item.calculosLibras?.enHopper?.toFixed(2) },
          { label: 'Floor', getValue: (item) => item.calculosLibras?.enPiso?.toFixed(2) },
          { label: 'Trays', getValue: (item) => item.calculosLibras?.enBandejas?.toFixed(2) },
          { label: 'FG Process', getValue: (item) => item.calculosLibras?.enProcesoTerminado?.toFixed(2) },
        ],
      },
    ],
    createTemplate: {
      id_turno: 1,
      item_chocolate_tanque: '10186',
      item_corriendo: '21101',
      moldes_llenados: 0,
      porcentaje_singles_banda: 100,
      porcentaje_tanque_morcos: 0,
      temper_unit_libras: 0,
      porcentaje_tanque_pti: 0,
      hopper_libras: 0,
      porcentaje_chocolate_piso: 0,
      total_peso_palet: 0,
      bandejas_con_chocolate: 0,
      producto_terminado_proceso: 0,
      total_chocolate_sistema: 0,
    },
    fields: [
      { name: 'id_turno', label: 'Shift', section: 'General', type: 'select', options: [{ value: 1, label: 'Shift 1' }, { value: 2, label: 'Shift 2' }, { value: 3, label: 'Shift 3' }] },
      {
        name: 'item_chocolate_tanque',
        label: 'Chocolate Type',
        section: 'General',
        type: 'select',
        optionsEndpoint: '/tipos-chocolate',
        getOptionValue: (item) => item.idTipo,
        getOptionLabel: (item) => `${item.idTipo} - ${item.categoria}`,
      },
      {
        name: 'item_corriendo',
        label: 'Running Item',
        section: 'General',
        type: 'select',
        optionsEndpoint: '/productos',
        getOptionValue: (item) => item.codigoItem,
        getOptionLabel: (item) => `${item.codigoItem} - ${item.descripcion}`,
      },
      { name: 'moldes_llenados', label: 'Molds filled', section: 'Production', type: 'number' },
      { name: 'porcentaje_singles_banda', label: '% Singles Piece on Belt', section: 'Production', type: 'number' },
      { name: 'bandejas_con_chocolate', label: 'Tray with Chocolate', section: 'Production', type: 'number' },
      { name: 'producto_terminado_proceso', label: 'Finished Product in Process', section: 'Production', type: 'number' },
      { name: 'porcentaje_tanque_morcos', label: '% Morcos Tank', section: 'Tanks & Floor', type: 'number' },
      { name: 'temper_unit_libras', label: 'Temper unit', section: 'Tanks & Floor', type: 'number', step: '0.01' },
      { name: 'porcentaje_tanque_pti', label: '% PTI Tank', section: 'Tanks & Floor', type: 'number' },
      { name: 'hopper_libras', label: 'Hopper', section: 'Tanks & Floor', type: 'number', step: '0.01' },
      { name: 'porcentaje_chocolate_piso', label: 'boxes on the floor chocolate', section: 'Tanks & Floor', type: 'number' },
      { name: 'total_peso_palet', label: 'total amount of chocolate on the floor', section: 'Tanks & Floor', type: 'number', step: '0.01', readOnly: true },
      { name: 'total_chocolate_sistema', label: 'Total System (lb)', section: 'System', type: 'number', step: '0.01' },
    ],
    toEditPayload: (item) => ({
      id_turno: item.turno,
      item_chocolate_tanque: item.tipoChocolate?.codigo,
      item_corriendo: item.producto?.codigo,
      moldes_llenados: item.insumos?.moldesLlenados,
      porcentaje_singles_banda: item.insumos?.porcentajeSinglesBanda,
      bandejas_con_chocolate: item.insumos?.bandejasConChocolate,
      producto_terminado_proceso: item.insumos?.productoTerminadoProceso,
      porcentaje_tanque_morcos: item.insumos?.porcentajeTanqueMorcos,
      temper_unit_libras: item.insumos?.temperUnitLibras,
      porcentaje_tanque_pti: item.insumos?.porcentajeTanquePti,
      hopper_libras: item.insumos?.hopperLibras,
      porcentaje_chocolate_piso: item.insumos?.porcentajeChocolatePiso,
      total_peso_palet: item.insumos?.totalPesoPalet,
      total_chocolate_sistema: item.totalesSistema?.totalChocolateTeoricoSistema,
    }),
  },
  productos: {
    id: 'productos',
    title: 'Products',
    eyebrow: 'Catalog',
  endpoint: '/productos',
  getId: (item) => item.codigoItem,
  getTitle: (item) => item.codigoItem,
  getSubtitle: (item) => item.descripcion,
  stickyFilterColumns: 3,
  listColumnFilters: [
    {
      label: 'PRODUCT SPECIFICATIONS',
      columns: [
        { label: '#', getValue: (item, index) => index + 1 },
        { label: 'Update', getValue: (item) => timeAgo(item.fechaActualizacion) },
        { label: 'ITEM', getValue: (item) => item.codigoItem },
        { label: 'DESCRIPTION', getValue: (item) => item.descripcion },
        { label: 'GRAMS PER SINGLE PIECE', getValue: (item) => item.peso?.gramos },
      ],
    },
    {
      label: 'MOLDS',
      columns: [
        { label: 'MOLD ITEM', getValue: (item) => item.maquinaria?.molde },
        { label: 'TOTAL MOLDS', getValue: (item) => item.maquinaria?.totalMoldes },
        { label: 'UNITS/MOLD', getValue: (item) => item.maquinaria?.unidadesPorMolde, inlineEdit: 'unidades_por_molde' },
      ],
    },
    {
      label: 'BELT & GONDOLA DISTRIBUTION',
      columns: [
        { label: 'MOLDS ON BELT', getValue: (item) => item.maquinaria?.moldesEnBanda, inlineEdit: 'moldes_en_banda' },
        { label: 'SINGLES PIECES ON BELT', getValue: (item) => item.maquinaria?.piezasEnBanda, calculated: true },
      ],
    },
  ],
  createTemplate: {
    item: '',
    descripcion: '',
    single_item: '',
    gramos_por_pieza: 0,
    libras_pieza_chocolate: 0,
    libras_pieza_arroz: 0,
    piezas_caja: 0,
    piezas_display: 0,
    item_molde: '',
    total_moldes: 0,
    unidades_por_molde: 0,
    moldes_en_banda: 0,
    piezas_singles_en_banda: 0,
  },
  fields: [
    { name: 'item', label: 'Item', section: 'General', createOnly: true },
    { name: 'descripcion', label: 'Description', section: 'General', type: 'textarea' },
    { name: 'single_item', label: 'Individual Item', section: 'General' },
    { name: 'gramos_por_pieza', label: 'Grams per Piece', section: 'Weight', type: 'number', step: '0.01' },
    { name: 'libras_pieza_chocolate', label: 'Chocolate lbs per Piece', section: 'Weight', type: 'number', step: '0.00001' },
    { name: 'libras_pieza_arroz', label: 'Rice lbs per Piece', section: 'Weight', type: 'number', step: '0.00001' },
    { name: 'piezas_caja', label: 'Pieces per Box', section: 'Packaging', type: 'number' },
    { name: 'piezas_display', label: 'Pieces per Display', section: 'Packaging', type: 'number' },
    { name: 'item_molde', label: 'Mold Item', section: 'Machinery' },
    { name: 'total_moldes', label: 'Total Molds', section: 'Machinery', type: 'number' },
    { name: 'unidades_por_molde', label: 'Units per Mold', section: 'Machinery', type: 'number' },
    { name: 'moldes_en_banda', label: 'Molds on Belt', section: 'Machinery', type: 'number' },
    { name: 'piezas_singles_en_banda', label: 'Singles Pieces on Belt', section: 'Machinery', type: 'number' },
  ],
  toEditPayload: (item) => ({
      descripcion: item.descripcion,
      single_item: item.itemIndividual,
      gramos_por_pieza: item.peso?.gramos,
      libras_pieza_chocolate: item.peso?.librasChocolate,
      libras_pieza_arroz: item.peso?.librasArroz,
      piezas_caja: item.empaque?.piezasPorCaja,
      piezas_display: item.empaque?.piezasPorDisplay,
      item_molde: item.maquinaria?.molde,
      total_moldes: item.maquinaria?.totalMoldes,
      unidades_por_molde: item.maquinaria?.unidadesPorMolde,
      moldes_en_banda: item.maquinaria?.moldesEnBanda,
      piezas_singles_en_banda: item.maquinaria?.piezasEnBanda,
    }),
  },
  tipos: {
    id: 'tipos',
    title: 'Chocolate Types',
    eyebrow: 'Catalog',
    endpoint: '/tipos-chocolate',
    idLabel: 'idTipo',
    getId: (item) => item.idTipo,
    getTitle: (item) => item.idTipo,
    getSubtitle: (item) => item.categoria,
    listFields: [
      { label: '#', getValue: (item, index) => index + 1 },
      { label: 'Update', getValue: (item) => timeAgo(item.fechaActualizacion) },
      { label: 'Code', getValue: (item) => item.idTipo },
      { label: 'Category', getValue: (item) => item.categoria },
    ],
    createTemplate: {
      id_tipo: '',
      nombre_tipo: '',
    },
    fields: [
      { name: 'id_tipo', label: 'Code', section: 'General', createOnly: true },
      { name: 'nombre_tipo', label: 'Category', section: 'General' },
    ],
    toEditPayload: (item) => ({
      nombre_tipo: item.categoria,
    }),
  },
  tanques: {
    id: 'tanques',
    title: 'Tanks',
    eyebrow: 'Capacity',
    endpoint: '/tanques',
    idLabel: 'nombre',
    getId: (item) => item.nombre,
    getTitle: (item) => item.nombre,
    getSubtitle: (item) => `${item.capacidadLibras} lb`,
    listFields: [
      { label: '#', getValue: (item, index) => index + 1 },
      { label: 'Update', getValue: (item) => timeAgo(item.fechaActualizacion) },
      { label: 'Name', getValue: (item) => item.nombre },
      { label: 'Capacity (lb)', getValue: (item) => item.capacidadLibras },
    ],
    createTemplate: {
      nombre_tanque: '',
      capacidad_libras: 0,
    },
    fields: [
      { name: 'nombre_tanque', label: 'Name', section: 'General', createOnly: true },
      { name: 'capacidad_libras', label: 'Capacity (lb)', section: 'General', type: 'number', step: '0.01' },
    ],
    toEditPayload: (item) => ({
      capacidad_libras: item.capacidadLibras,
    }),
  },
}
